<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: 17. januar 2023 21:14:26</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "C:\Users\au687527\GitHub\GreenGDP\gis\script_module.py", line 88, in get_data
    urllib.request.urlretrieve(url, f)
AttributeError: module 'urllib' has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\au687527\GitHub\GreenGDP\gis\script.py", line 79, in &lt;module&gt;
    c.get_data()
  File "C:\Users\au687527\GitHub\GreenGDP\gis\script_module.py", line 89, in get_data
    except urllib.error.URLError as e:
AttributeError: module 'urllib' has no attribute 'error'
</msg><msg code="0" type="0">Failed script WaterbodiesScriptTool...</msg><msg code="-2147467259" type="100">Failed to execute (WaterbodiesScriptTool).</msg><msg code="0" type="3">Failed at 17. januar 2023 21:14:31 (Elapsed Time: 4,37 seconds)</msg></messages>